# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cpiapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_3723c09ad76e43b1b34c9c1d5d88727e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_56c672f69d1647afb883bea99d6c1b65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3723c09ad76e43b1b34c9c1d5d88727e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cpiapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e6efb041d7b41e59ef1e6c74c4b4934 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_3723c09ad76e43b1b34c9c1d5d88727e }}/appsvc/staticsite:${{ github.sha }}'